### ISSUE TITLE
fisher and stow doesn't work properly

### ISSUE THREAD

**Issue by amir20** [jorgebucaran/fisher#460]
I use [stow](http://www.gnu.org/software/stow/) to store my dotfiles in [GitHub](https://github.com/amir20/.dotfiles/blob/master/fisher/.config/fish/fishfile) and run [stow](https://github.com/amir20/.dotfiles/blob/master/bootstrap.sh#L22) to symbolic link my `fishfile`. 

In version 2, this used to work just fine. But it looks like in v3, symbolic files are no longer supported. After running fisher, the file is removed and replaced with a new file. 

Here is what I mean: 

```
$ la ~/.config/fish/fishfile
lrwxr-xr-x    44 amirraminfar staff  6 Oct 12:18   -- /Users/amirraminfar/.config/fish/fishfile -> ../../.dotfiles/fisher/.config/fish/fishfile
```

After running `fisher`: 

```
.rw-r--r--   289 amirraminfar staff  6 Oct 12:19  /Users/amirraminfar/.config/fish/fishfile
```

So it is removed and replaced with a new file. 

:(

**Comment by jorgebucaran** [comment]
@amir20 Does updating the real file (without creating a new file) solve this issue?

Before re-writing the fishfile we can check if it's a symbolic link and get the path to the real file using `readlink` if that's the case. Else, proceed as usual.

**Comment by amir20** [comment]
> @amir20 Does updating the real file (without creating a new file) solve this issue?

@jorgebucaran yes that works. That's what it used to do. 

I think right now, you replace the file. So that would work if you get the real path. Can you also truncate the file instead and just rewrite to the same file? Not sure how that would work.

**Comment by jorgebucaran** [comment]
@amir20 Fixed in 3.0.6 73505e7 🎉

Update to the latest version with `fisher self-update`.

**Comment by amir20** [comment]
Hmmm after the update. It looks like it still doesn't work. Here is a screenshot. 

<img width="1207" alt="screen shot 2018-10-07 at 9 36 32 am" src="https://user-images.githubusercontent.com/260667/46584174-e0888480-ca14-11e8-9d8f-a5b1dd5642b1.png">

The error is 

```
<W> fish: An error occurred while redirecting file '../../.dotfiles/fisher/.config/fish/fishfile'
open: No such file or directory
mv: rename ../../.dotfiles/fisher/.config/fish/fishfile@ to ../../.dotfiles/fisher/.config/fish/fishfile: No such file or directory
<W> fish: An error occurred while redirecting file '../../.dotfiles/fisher/.config/fish/fishfile'
open: No such file or directory
nothing to commit -- try adding some packages
```

It doesn't like the symbolic link.

**Comment by jorgebucaran** [comment]
@amir20 The only code I added was:

```fish
else if test -L "$fishfile"
        set fishfile (command readlink $fishfile)
```

Isn't your fishfile a symbolic link?

**Comment by amir20** [comment]
```
$ readlink ~/.config/fish/fishfile
../../.dotfiles/fisher/.config/fish/fishfile
```

I think you need `realpath`

```
$ realpath ~/.config/fish/fishfile
/Users/amirraminfar/.dotfiles/fisher/.config/fish/fishfile
```

**Comment by amir20** [comment]
Actually let me just try with `realpath`

**Comment by amir20** [comment]
Yup, that works! 👍 Do you want a PR?

**Comment by jorgebucaran** [comment]
@amir20 Yes if you know how to do it without `realpath`, which we can't use.

**Comment by jorgebucaran** [comment]
@amir20 ould Could you enter the absolute path to your fishfile here? I am trying to understand `readlink`'s output. Is it the path relative from $PWD what it prints?

**Comment by amir20** [comment]
The absolute path is in comment https://github.com/jorgebucaran/fisher/issues/460#issuecomment-427668049 which is `/Users/amirraminfar/.dotfiles/fisher/.config/fish/fishfile`

I am not sure how to do it without `realpath`? Is that a MacOs thing?

**Comment by jorgebucaran** [comment]
@amir20 My friend a portable `realpath` is tough. 

Maybe @faho has any idea? 🤔

**Comment by amir20** [comment]
I don't think I understand why it needs to be without `realpath`. Is that command not available on other systems?

**Comment by jorgebucaran** [comment]
@amir20 I believe it isn't. See https://github.com/fish-shell/fish-shell/blob/master/share/functions/realpath.fish.

**Comment by amir20** [comment]
Hmmmm 🤔

**Comment by jorgebucaran** [comment]
I'll fix this tomorrow. If I can't, then I'll use `realpath` and note it in the README that it's only available in fish 2.3 or something. 

@amir20 BTW when you ran `readlink ~/.config/fish/fishfile`, what was your current working directory? I am trying to figure out if readlink's output is always relative to the current working directory.

**Comment by jorgebucaran** [comment]
Here is fish .cpp implementation of the `realpath` built-in for the record.

https://github.com/fish-shell/fish-shell/blob/72d80c3d91bbd35bed0aafb5514c9834bb48e256/src/builtin_realpath.cpp

**Comment by jorgebucaran** [comment]
@amir20 IIRC, V2 didn't use `realpath` either. So, the solution must be there.

**Comment by amir20** [comment]
```
$ ~ > custom_realpath  ~/.config/fish/fishfile                                                                                                       14:26
/Users/amirraminfar/.config/fish/fishfile
```

This should work. I tried it out. 

@jorgebucaran I am just curious about one thing though. It looks like fish version of `realpath` has been available since 2016 https://github.com/fish-shell/fish-shell/commit/6c329e8a839c1b5eeaf2e545b4f4084c3a8830f7#diff-2839f3e931401ddeb9e93c336c2c5109. Is it worth creating a custom version. Aren't the majority of users already on the latest fishshell? That would make it easier if you can just `realpath` being there.

**Comment by jorgebucaran** [comment]
It would and I want to say to hell with it and drop 2.0~2.2 support. On the other hand, it’s amazing fisher works with any fish you can throw at it (except for this issue perhaps). 

IIRC Ubuntu is still stuck on 2.2 by default. 

The good news is that dropping support for old fish is bound to happen sooner or later. The question is when?

So, when? Next year? 2020 for a nice round number?

**Comment by jorgebucaran** [comment]
@amir20 As it turns out, we don't need to use readlink or realpath. We can simply write to the file directly.

**Comment by jorgebucaran** [comment]
@amir20 Fixed in 3.0.6 f75de3a 🎉

**Comment by amir20** [comment]
Nice 🎉And it works! Glad to see there was a similar solution. But I think that's what I had in mind [above](https://github.com/jorgebucaran/fisher/issues/460#issuecomment-427618966) 

> I think right now, you replace the file. So that would work if you get the real path. Can you also truncate the file instead and just rewrite to the same file? Not sure how that would work.

**Comment by jorgebucaran** [comment]
@amir20 Yeah, you did! :) 💯
